### ISSUE TITLE
SQLite doesn't save player data

### ISSUE THREAD

**Issue by kupoback** [yonilerner/cs2-retakes-allocator#152]
Using the default Database provide information on dathost.net, when the server restarts all player preferences are wiped. There's no creation of the SQLite database file anywhere in the install.

**Comment by yonilerner** [comment]
Thats because the default location is the same folder as the game executable, which on dathost is part of the system that isnt persistent.

Your problem should go away if you change the location of the database file to somewhere persistent. For example, on my dathost server, I use `"Data Source=../../csgo/data.db"`

**Comment by kupoback** [comment]
Thank you very much for this solution. The pathing didn't make much sense and Dathost didn't have anything outlined about it's structure path.
