### ISSUE TITLE
Buy Menu Bug Choosing wrong weapon

### ISSUE THREAD

**Issue by evenbreak** [yonilerner/cs2-retakes-allocator#88]
The last update was life saving, thanks! but i still facing this problem, for example, half buy im using mac 10 but i want buy ump for example, the game wont let me, if i click in ump, the game gonna give me for example mp7 

same goes for pistol round, if i want a tec 9 or glock, it wont let me, only buy deagle for example

or when im in full round and i choose to change my secondary(deagle) to any other weapon, the same error [BrutalCSEjziponken](https://github.com/BrutalCSEjziponken) < https://discord.com/channels/1160907911501991946/1193311939862986792/1200719109327958149 happens 

My Json
[config.json](https://github.com/yonilerner/cs2-retakes-allocator/files/14077400/config.json)

**Comment by yonilerner** [comment]
Hey, I think its because you have `"AllowAllocationAfterFreezeTime": false`. This means that if you try to buy once the round actually starts, you wont be able to. If you set that to `true`, you will be able to buy all round

I do need to fix what happens when you arent allowed to buy - I should give back the gun you had before instead of a random one. So I will fix that. But I think this is why its happening to you

**Comment by evenbreak** [comment]
> Hey, I think its because you have `"AllowAllocationAfterFreezeTime": false`. This means that if you try to buy once the round actually starts, you wont be able to. If you set that to `true`, you will be able to buy all round
> 
> I do need to fix what happens when you arent allowed to buy - I should give back the gun you had before instead of a random one. So I will fix that. But I think this is why its happening to you

Thank you, changint Allowallocationafterfreezetime to true indeed worked great! 

For now i still havent faced any issue with not being able to buy, but if i do, i will tell u!, thanks

**Comment by yonilerner** [comment]
Sounds good. Ill close this issue for now but feel free to reopen if you need more help or find problems.
